os:
  - linux
  - osx
language: python
env:
  global:
    - PACKAGE="LSL" # TODO: fix
  matrix:
    - SUBLIME_TEXT_VERSION="3"
python:
  - "3.3"
matrix:
  include:
    - os: linux
      python: 3.3
before_install:
# - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
  - curl -OL https://raw.githubusercontent.com/gerardroche/UnitTesting/develop/sbin/travis.sh
install:
  - pip install flake8
  - pip install pep257
  - sh travis.sh bootstrap --with-color-scheme-unit
script:
  - flake8 . --max-line-length=120 --ignore=F401,F403
  - pep257 . --add-ignore=D202
  - sh travis.sh run_color_scheme_tests
# - sh travis.sh run_tests
notifications:
  email: false
